- name: create volume {{ item['name'] }}
  file:
    path: "{{ item['path'] }}"
    owner: "{{ item['owner'] | default(nomad_user) }}"
    group: "{{ item['group'] | default(nomad_group) }}"
    state: directory
    mode: "{{ item['mode'] | default('0644') }}"
  with_items: "{{ nomad_host_volumes }}"
  when: item['change_mode'] | default('true') | bool
